# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(971, 828)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../TermProject/resource/small_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 241, 431))
        self.groupBox.setObjectName("groupBox")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 221, 221))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../TermProject/resource/myLogo2.png"))
        self.label_4.setObjectName("label_4")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(10, 280, 221, 141))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.loginButton = QtWidgets.QPushButton(self.groupBox)
        self.loginButton.setGeometry(QtCore.QRect(10, 233, 221, 41))
        self.loginButton.setObjectName("loginButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 430, 941, 361))
        self.groupBox_2.setObjectName("groupBox_2")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.groupBox_2)
        self.calendarWidget.setGeometry(QtCore.QRect(10, 20, 351, 331))
        self.calendarWidget.setObjectName("calendarWidget")
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setGeometry(QtCore.QRect(362, 20, 16, 331))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 19, 121, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.line_5 = QtWidgets.QFrame(self.groupBox_2)
        self.line_5.setGeometry(QtCore.QRect(380, 46, 551, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(520, 19, 161, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.line_7 = QtWidgets.QFrame(self.groupBox_2)
        self.line_7.setGeometry(QtCore.QRect(502, 20, 16, 31))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit.setGeometry(QtCore.QRect(380, 60, 551, 291))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.line_8 = QtWidgets.QFrame(self.groupBox_2)
        self.line_8.setGeometry(QtCore.QRect(682, 20, 16, 31))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(700, 19, 111, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.line_9 = QtWidgets.QFrame(self.groupBox_2)
        self.line_9.setGeometry(QtCore.QRect(812, 19, 16, 31))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(260, 10, 691, 421))
        self.groupBox_3.setObjectName("groupBox_3")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox.setGeometry(QtCore.QRect(340, 20, 91, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(10, 20, 311, 391))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_3.setGeometry(QtCore.QRect(620, 60, 61, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_2.setGeometry(QtCore.QRect(340, 61, 271, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.line_4 = QtWidgets.QFrame(self.groupBox_3)
        self.line_4.setGeometry(QtCore.QRect(321, 10, 20, 411))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(340, 100, 71, 31))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(340, 130, 341, 281))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(242, 10, 16, 421))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(950, 18, 20, 771))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "I♥KOREA"))
        self.groupBox.setTitle(_translate("MainWindow", "인증 및 로그"))
        self.plainTextEdit_2.setPlainText(_translate("MainWindow", "로그\n"
""))
        self.loginButton.setText(_translate("MainWindow", "인증"))
        self.groupBox_2.setTitle(_translate("MainWindow", "달력 및 메모장, 홈페이지 검색과 이메일 전송"))
        self.pushButton_2.setText(_translate("MainWindow", "홈페이지 검색"))
        self.pushButton_4.setText(_translate("MainWindow", "여행정보 이메일 전송"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "메모\n"
""))
        self.pushButton_5.setText(_translate("MainWindow", "메모장 초기화"))
        self.groupBox_3.setTitle(_translate("MainWindow", "여행정보 검색 및 이미지 미리보기"))
        self.comboBox.setItemText(0, _translate("MainWindow", "지역선택"))
        self.comboBox.setItemText(1, _translate("MainWindow", "서울"))
        self.comboBox.setItemText(2, _translate("MainWindow", "인천"))
        self.comboBox.setItemText(3, _translate("MainWindow", "대전"))
        self.comboBox.setItemText(4, _translate("MainWindow", "대구"))
        self.comboBox.setItemText(5, _translate("MainWindow", "부산"))
        self.comboBox.setItemText(6, _translate("MainWindow", "울산"))
        self.comboBox.setItemText(7, _translate("MainWindow", "경기도"))
        self.comboBox.setItemText(8, _translate("MainWindow", "강원도"))
        self.comboBox.setItemText(9, _translate("MainWindow", "충청북도"))
        self.comboBox.setItemText(10, _translate("MainWindow", "충청남도"))
        self.comboBox.setItemText(11, _translate("MainWindow", "경상북도"))
        self.comboBox.setItemText(12, _translate("MainWindow", "경상남도"))
        self.comboBox.setItemText(13, _translate("MainWindow", "전라북도"))
        self.comboBox.setItemText(14, _translate("MainWindow", "전라남도"))
        self.comboBox.setItemText(15, _translate("MainWindow", "제주도"))
        self.plainTextEdit_3.setPlainText(_translate("MainWindow", "여행정보\n"
""))
        self.pushButton_3.setText(_translate("MainWindow", "검색"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "여행장소"))
        self.label_3.setText(_translate("MainWindow", "▼이미지▼"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

